import { Country } from '@/types';

export const countries: Country[] = [
  { name: 'Argentina', code: 'AR', emoji: '🇦🇷' },
  { name: 'Australia', code: 'AU', emoji: '🇦🇺' },
  { name: 'Austria', code: 'AT', emoji: '🇦🇹' },
  { name: 'Belgium', code: 'BE', emoji: '🇧🇪' },
  { name: 'Brazil', code: 'BR', emoji: '🇧🇷' },
  { name: 'Canada', code: 'CA', emoji: '🇨🇦' },
  { name: 'Chile', code: 'CL', emoji: '🇨🇱' },
  { name: 'China', code: 'CN', emoji: '🇨🇳' },
  { name: 'Colombia', code: 'CO', emoji: '🇨🇴' },
  { name: 'Cuba', code: 'CU', emoji: '🇨🇺' },
  { name: 'Czech Republic', code: 'CZ', emoji: '🇨🇿' },
  { name: 'Denmark', code: 'DK', emoji: '🇩🇰' },
  { name: 'Egypt', code: 'EG', emoji: '🇪🇬' },
  { name: 'Finland', code: 'FI', emoji: '🇫🇮' },
  { name: 'France', code: 'FR', emoji: '🇫🇷' },
  { name: 'Germany', code: 'DE', emoji: '🇩🇪' },
  { name: 'Greece', code: 'GR', emoji: '🇬🇷' },
  { name: 'Hungary', code: 'HU', emoji: '🇭🇺' },
  { name: 'Iceland', code: 'IS', emoji: '🇮🇸' },
  { name: 'India', code: 'IN', emoji: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', emoji: '🇮🇩' },
  { name: 'Ireland', code: 'IE', emoji: '🇮🇪' },
  { name: 'Israel', code: 'IL', emoji: '🇮🇱' },
  { name: 'Italy', code: 'IT', emoji: '🇮🇹' },
  { name: 'Jamaica', code: 'JM', emoji: '🇯🇲' },
  { name: 'Japan', code: 'JP', emoji: '🇯🇵' },
  { name: 'Kenya', code: 'KE', emoji: '🇰🇪' },
  { name: 'Mexico', code: 'MX', emoji: '🇲🇽' },
  { name: 'Morocco', code: 'MA', emoji: '🇲🇦' },
  { name: 'Netherlands', code: 'NL', emoji: '🇳🇱' },
  { name: 'New Zealand', code: 'NZ', emoji: '🇳🇿' },
  { name: 'Nigeria', code: 'NG', emoji: '🇳🇬' },
  { name: 'Norway', code: 'NO', emoji: '🇳🇴' },
  { name: 'Peru', code: 'PE', emoji: '🇵🇪' },
  { name: 'Poland', code: 'PL', emoji: '🇵🇱' },
  { name: 'Portugal', code: 'PT', emoji: '🇵🇹' },
  { name: 'Romania', code: 'RO', emoji: '🇷🇴' },
  { name: 'Russia', code: 'RU', emoji: '🇷🇺' },
  { name: 'Senegal', code: 'SN', emoji: '🇸🇳' },
  { name: 'South Africa', code: 'ZA', emoji: '🇿🇦' },
  { name: 'South Korea', code: 'KR', emoji: '🇰🇷' },
  { name: 'Spain', code: 'ES', emoji: '🇪🇸' },
  { name: 'Sweden', code: 'SE', emoji: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', emoji: '🇨🇭' },
  { name: 'Thailand', code: 'TH', emoji: '🇹🇭' },
  { name: 'Turkey', code: 'TR', emoji: '🇹🇷' },
  { name: 'Ukraine', code: 'UA', emoji: '🇺🇦' },
  { name: 'United Kingdom', code: 'GB', emoji: '🇬🇧' },
  { name: 'United States', code: 'US', emoji: '🇺🇸' },
  { name: 'Vietnam', code: 'VN', emoji: '🇻🇳' },
];

export function getRandomCountry(): Country {
  return countries[Math.floor(Math.random() * countries.length)];
}
